/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;
import Utility.sessionManager;
import javax.swing.JOptionPane;
/**
 *
 * @author ridho.naibaho
 */
public class main_form extends javax.swing.JFrame {
    private SimpleDateFormat formatter;
    private volatile boolean running = true;
    /**
     * Creates new form main_form
     */
    public main_form() {
        initComponents();
        checkSession();
        setLocationRelativeTo(null);
        
        formatter = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");
        
        Thread threadJam = new Thread(() -> {
            while (running) {
                Date sekarang = new Date();
                SwingUtilities.invokeLater(() -> lblCurrentTime.setText(formatter.format(sekarang)));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    running = false;
                }
            }
        });
        threadJam.start();
    }
    
    private void checkSession() {
        if (!sessionManager.isLoggedIn()) {
            login_user loginForm = new login_user();
            loginForm.setVisible(true);
            this.dispose(); 
        } else {
            String userId = sessionManager.getLoggedInUserId();
            lblLoginUser.setText("Welcome Back : "+ userId +" ");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        lblLoginUser = new javax.swing.JLabel();
        lblCurrentTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnPelanggan = new javax.swing.JMenuItem();
        mnBarang = new javax.swing.JMenuItem();
        mnKasir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnNota = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pemrograman Visual");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Aplikasi Penjualan");

        jToolBar1.setRollover(true);
        jToolBar1.add(lblLoginUser);
        jToolBar1.add(lblCurrentTime);

        jMenu3.setText("File");

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu3.add(mnLogout);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Master");

        mnPelanggan.setText("Pelanggan");
        mnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(mnPelanggan);

        mnBarang.setText("Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        jMenu1.add(mnBarang);

        mnKasir.setText("Kasir");
        mnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasirActionPerformed(evt);
            }
        });
        jMenu1.add(mnKasir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        mnNota.setText("Nota");
        mnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNotaActionPerformed(evt);
            }
        });
        jMenu2.add(mnNota);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(212, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
       barang frmBarang = new barang();
       frmBarang.setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasirActionPerformed
        kasir frmKasir = new kasir();
        frmKasir.setVisible(true);
    }//GEN-LAST:event_mnKasirActionPerformed

    private void mnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPelangganActionPerformed
        pelanggan frmPelanggan = new pelanggan();
        frmPelanggan.setVisible(true);
    }//GEN-LAST:event_mnPelangganActionPerformed

    private void mnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNotaActionPerformed
        nota frmNota = new nota();
        frmNota.setVisible(true);
    }//GEN-LAST:event_mnNotaActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar aplikasi ?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (ok == JOptionPane.YES_OPTION) { 
            sessionManager.logoutUser();
            login_user loginForm = new login_user();
            loginForm.setVisible(true);
            this.dispose(); 
        }
    }//GEN-LAST:event_mnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(new FlatMacLightLaf());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblLoginUser;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenuItem mnKasir;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnNota;
    private javax.swing.JMenuItem mnPelanggan;
    // End of variables declaration//GEN-END:variables
}
